variables:
  DOCKER_DRIVER: overlay
 
stages:
  - execute

# Common template for on-call rotation jobs
.rotate_template:
  stage: execute
  image: alpine:latest
  before_script:
    - apk add --no-cache curl jq bash
  script:
    - chmod a+x push_into_slack_group.sh
    - ./push_into_slack_group.sh $PRIMARY_SCHEDULE $SECONDARY_SCHEDULE "$SLACK_GROUP"
  only:
    - master
  tags:
    - eks-eu-central-2-your_cluster

rotateOncallTeam_1:
  extends: .rotate_template
  variables:
    PRIMARY_SCHEDULE: "PXXXXXX"
    SECONDARY_SCHEDULE: "PYYYYYY"
    SLACK_GROUP: "Team_1 on-call"

rotateOncallTeam_2:
  extends: .rotate_template
  variables:
    PRIMARY_SCHEDULE: "PZZZZZZ"
    SECONDARY_SCHEDULE: "PUUUUUU"
    SLACK_GROUP: "Team_2 on-call"
